from django.core.management.base import BaseCommand
from api.models import Kebab


class Command(BaseCommand):
    help = "Seed database with initial kebab data"

    def handle(self, *args, **options):
        kebabs = [
            {
                "name": "Rulo Kebab",
                "description": "Popularny kebab w centrum Legnicy.",
                "latitude": 51.205062,
                "longitude": 16.154562,
                "status": "closed",
                "meats": "kurczak, wołowina, mieszane",
                "sauces": "łagodny, arabski, ostry, mieszany",
                "opening_year": None,
                "closing_year": None,
                "craft_rating": False,
                "in_chain": False,
                "order_methods": "na miejscu, na wynos",
                "location_details": "Przy ulicy Nowy Świat",
                "social_links": {
                    "pyszne_pl": "https://www.pyszne.pl/menu/rulo-kebab-legnica",
                    "glovo": "https://glovoapp.com/pl/pl/legnica/rulo-kebab-legnica/",
                },
                "logo": "kebab_logos/Rulo.png",
                "google_rating": None,
                "pyszne_rating": None,
            },
            {
                "name": "Kebab u Turasa",
                "description": "Popularny kebab na osiedlu.",
                "latitude": 51.200629,
                "longitude": 16.163493,
                "status": "closed",
                "meats": "kurczak, wołowina",
                "sauces": "łagodny, ostry, czosnkowy",
                "opening_year": 2018,
                "closing_year": None,
                "craft_rating": False,
                "in_chain": False,
                "order_methods": "na wynos",
                "location_details": "Romualda Traugutta 24",
                "social_links": None,
                "google_rating": 5.0,
                "pyszne_rating": 4.05,
                "logo": None,
            },
            {
                "name": "Kebab domowy Maru",
                "description": "Nowo otwarty kebab w Legnicy.",
                "latitude": 51.209084,
                "longitude": 16.171741,
                "status": "planned",
                "meats": "kurczak",
                "sauces": "łagodny, ostry",
                "opening_year": 2025,
                "closing_year": None,
                "craft_rating": False,
                "in_chain": False,
                "order_methods": "na wynos",
                "location_details": "Wrocławska 41A",
                "social_links": None,
                "google_rating": 0.0,
                "pyszne_rating": 0.0,
                "logo": None,
            },
            {
                "name": "Kebab&Gyros",
                "description": "Kebab i gyros w jednym miejscu.",
                "latitude": 51.185456,
                "longitude": 16.172375,
                "status": "open",
                "meats": "kurczak, wołowina, wieprzowina",
                "sauces": "łagodny, ostry, mieszany",
                "opening_year": 2010,
                "closing_year": None,
                "craft_rating": False,
                "in_chain": False,
                "order_methods": "na miejscu, na wynos",
                "location_details": "Roberta Schumana 17",
                "social_links": None,
                "google_rating": 3.1,
                "pyszne_rating": 3.9,
                "logo": None,
            },
            {
                "name": "Stambuł Kebab",
                "description": "Klasyczny kebab turecki.",
                "latitude": 51.207187,
                "longitude": 16.156937,
                "status": "exists",
                "meats": "kurczak, wołowina, mieszane, falafel",
                "sauces": "łagodny, ostry, mieszany, czosnek, ziołowy",
                "opening_year": None,
                "closing_year": None,
                "craft_rating": False,
                "in_chain": False,
                "order_methods": "na miejscu, na wynos, dostawa",
                "location_details": "Chojnowska 21A",
                "social_links": {
                    "pyszne_pl": "https://www.pyszne.pl/menu/kebab-stambul-legnica-gwarna",
                },
                "google_rating": None,
                "pyszne_rating": None,
                "logo": "kebab_logos/Stambul.png",
            },
            {
                "name": "Leo Kebab",
                "description": "Kebab z szerokim wyborem mięsa i sosów.",
                "latitude": 51.204437,
                "longitude": 16.159937,
                "status": "exists",
                "meats": "kurczak, wołowina, mieszane, falafel, kapsalon",
                "sauces": "łagodny, mieszany, ostry",
                "opening_year": None,
                "closing_year": None,
                "craft_rating": False,
                "in_chain": True,
                "order_methods": "na miejscu, na wynos, dostawa",
                "location_details": "Jaworzyńska 4",
                "social_links": {
                    "glovo": "https://glovoapp.com/pl/pl/legnica/leo-kebab-legnica-lga/",
                    "pyszne_pl": "https://www.pyszne.pl/menu/leo-kebab-and-grill",
                },
                "google_rating": None,
                "pyszne_rating": None,
                "logo": "kebab_logos/Leo.png",
            },
            {
                "name": "Maxi Kebab",
                "description": "Kebab na parkingu Carrefoura.",
                "latitude": 51.201062,
                "longitude": 16.214813,
                "status": "exists",
                "meats": "kurczak, baran, mieszane",
                "sauces": "łagodny, czosnkowy, miętowy, ostry, mieszany, musztardowy",
                "opening_year": None,
                "closing_year": None,
                "craft_rating": True,
                "in_chain": False,
                "order_methods": "na miejscu, na wynos",
                "location_details": "Carrefour, aleja Piłsudskiego 84",
                "social_links": None,
                "google_rating": None,
                "pyszne_rating": None,
                "logo": "kebab_logos/Maxi.png",
            },
            {
                "name": "Bejrut Restauracja Libańska",
                "description": "Libańska restauracja z kebabem i falafelem.",
                "latitude": 51.205188,
                "longitude": 16.185313,
                "status": "exists",
                "meats": "kurczak, wołowina, mieszane, falafel",
                "sauces": "łagodny, mieszany, ostry, czosnkowy",
                "opening_year": None,
                "closing_year": None,
                "craft_rating": True,
                "in_chain": True,
                "order_methods": "na miejscu, na wynos, dostawa",
                "location_details": "aleja Piłsudskiego 18",
                "social_links": {
                    "glovo": "https://glovoapp.com/pl/pl/legnica/bejrut-restauracja-libanska-lga/",
                    "pyszne_pl": "https://www.pyszne.pl/menu/bejrut-restauracja-libanska-legnica",
                },
                "google_rating": None,
                "pyszne_rating": None,
                "logo": "kebab_logos/Bejrut.png",
            },
            {
    "name": "Hallo Kebap",
    "description": "Kebab oferujący różne sosy i opcje mięsne.",
    "latitude": 51.211687,
    "longitude": 16.175187,
    "status": "exists",
    "meats": "kurczak, wołowina, mieszane",
    "sauces": "ostry, czosnkowy, jogurtowy, ketchup",
    "opening_year": None,
    "closing_year": None,
    "craft_rating": True,
    "in_chain": True,
    "order_methods": "na miejscu, na wynos, dostawa",
    "location_details": "Stefana Czarnieckiego 19c",
    "social_links": {
        "pyszne_pl": "https://www.pyszne.pl/menu/hallo-kebap-legnica"
    },
    "google_rating": None,
    "pyszne_rating": None,
    "logo": "kebab_logos/Hallo.png",
},
{
    "name": "Dino Kebab",
    "description": "Kebab przy ulicy Jaworzyńska z różnorodnymi opcjami.",
    "latitude": 51.200688,
    "longitude": 16.159438,
    "status": "exists",
    "meats": "kurczak, wołowina, mieszane, falafel, kapsalon",
    "sauces": "łagodny, ostry, mieszany",
    "opening_year": None,
    "closing_year": None,
    "craft_rating": False,
    "in_chain": False,
    "order_methods": "na miejscu, na wynos, dostawa",
    "location_details": "Jaworzyńska 41",
    "social_links": {
        "pyszne_pl": "https://www.pyszne.pl/menu/kebab-dino",
        "glovo": "https://glovoapp.com/pl/pl/legnica/dino-kebab1-lga/"
    },
    "google_rating": None,
    "pyszne_rating": None,
    "logo": "kebab_logos/Dino.png",
},
{
    "name": "Am Am Kebab",
    "description": "Kebab z bogatym wyborem w Legnicy.",
    "latitude": 51.209563,
    "longitude": 16.187063,
    "status": "exists",
    "meats": "kurczak, wołowina, mieszane, falafel",
    "sauces": "łagodny, mieszany, ostry",
    "opening_year": None,
    "closing_year": None,
    "craft_rating": False,
    "in_chain": True,
    "order_methods": "na miejscu, na wynos, dostawa",
    "location_details": "Wrocławska 155",
    "social_links": {
        "pyszne_pl": "https://www.pyszne.pl/menu/am-am-kebab-legnica-wroclawska"
    },
    "google_rating": None,
    "pyszne_rating": None,
    "logo": "kebab_logos/AmAm.png",
},
{
    "name": "Lara Doner Kebab",
    "description": "Smaczny kebab w Legnicy z dobrymi opiniami.",
    "latitude": 51.209563,
    "longitude": 16.167813,
    "status": "exists",
    "meats": "kurczak, wołowina, mieszane, falafel",
    "sauces": "łagodny, ostry, mieszany, czosnkowy, ziołowy",
    "opening_year": None,
    "closing_year": None,
    "craft_rating": True,
    "in_chain": True,
    "order_methods": "na miejscu, na wynos",
    "location_details": "Wrocławska 13",
    "social_links": {
        "glovo": "https://glovoapp.com/pl/pl/legnica/lara-doner-kebab-lga/"
    },
    "google_rating": None,
    "pyszne_rating": None,
    "logo": "kebab_logos/Lara.png",
},
{
    "name": "Kebab Truck",
    "description": "Kebab mobilny przy ulicy Iwaszkiewicza.",
    "latitude": 51.207937,
    "longitude": 16.213437,
    "status": "exists",
    "meats": "kurczak, mieszane",
    "sauces": "czosnkowy, ziołowy, ostry, turecki",
    "opening_year": None,
    "closing_year": None,
    "craft_rating": True,
    "in_chain": False,
    "order_methods": "na miejscu, na wynos",
    "location_details": "Iwaszkiewicza 1",
    "social_links": None,
    "google_rating": None,
    "pyszne_rating": None,
    "logo": None,
},
{
    "name": "Kavovarka Kebab Kraft",
    "description": "Kebab w wersji kraftowej.",
    "latitude": 51.205562,
    "longitude": 16.186563,
    "status": "exists",
    "meats": "kurczak, wieprzowina, kraftowy",
    "sauces": "łagodny, ostry, czosnkowy",
    "opening_year": None,
    "closing_year": None,
    "craft_rating": True,
    "in_chain": False,
    "order_methods": "na miejscu, na wynos, dostawa",
    "location_details": "Górnicza 10B",
    "social_links": {
        "glovo": "https://glovoapp.com/pl/en/legnica/kavovarka-lga/"
    },
    "google_rating": None,
    "pyszne_rating": None,
    "logo": None,
}





        ]