# Generated by Django 4.2.5 on 2025-01-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_suggestion_suggestion_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kebab',
            name='opening_hours',
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('kebab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='api.kebab')),
            ],
        ),
    ]
