# Generated by Django 4.2.5 on 2025-01-09 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_kebab_in_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebab',
            name='google_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kebab',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='kebab',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='kebab_logos/'),
        ),
        migrations.AddField(
            model_name='kebab',
            name='pyszne_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kebab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.kebab')),
            ],
        ),
    ]
