# Generated by Django 4.2.5 on 2025-01-12 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_kebab_google_rating_kebab_last_updated_kebab_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='openinghour',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='openinghour',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='openinghour',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='user_name',
        ),
        migrations.AddField(
            model_name='openinghour',
            name='hours',
            field=models.JSONField(default='9:00 AM - 5:00 PM', help_text="JSON format: {'monday': {'open': '10:00', 'close': '20:00'}, 'tuesday': {'open': '10:00', 'close': '20:00'}, ...}"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kebab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kebab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kebab')},
            },
        ),
    ]
