# Generated by Django 4.2.5 on 2025-01-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_comment_usercomment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghour',
            name='hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='kebab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kebab'),
        ),
    ]
