# Generated by Django 4.2.5 on 2025-01-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_openinghour_hours_alter_openinghour_kebab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghour',
            name='hours',
            field=models.JSONField(default={'friday': {'close': '00:00', 'open': '00:00'}, 'monday': {'close': '00:00', 'open': '00:00'}, 'saturday': {'close': '00:00', 'open': '00:00'}, 'sunday': {'close': '00:00', 'open': '00:00'}, 'thursday': {'close': '00:00', 'open': '00:00'}, 'tuesday': {'close': '00:00', 'open': '00:00'}, 'wednesday': {'close': '00:00', 'open': '00:00'}}),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='kebab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openinghour_set', to='api.kebab'),
        ),
    ]
