# Generated by Django 4.2.5 on 2025-01-15 15:31

from django.db import migrations

def create_sample_opening_hours(apps, schema_editor):
    Kebab = apps.get_model('api', 'Kebab')
    OpeningHour = apps.get_model('api', 'OpeningHour')

    # Sample kebab IDs (assuming there are kebabs with these IDs)
    kebab_ids = [4]  # Replace with actual kebab IDs

    for kebab_id in kebab_ids:
        OpeningHour.objects.update(
            kebab_id=kebab_id,
            hours={
                "monday": {"open": "11:00", "close": "22:00"},
                "tuesday": {"open": "10:00", "close": "22:00"},
                "wednesday": {"open": "10:00", "close": "22:00"},
                "thursday": {"open": "10:00", "close": "22:00"},
                "friday": {"open": "10:00", "close": "23:00"},
                "saturday": {"open": "10:00", "close": "23:00"},
                "sunday": {"open": "10:00", "close": "20:00"},
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_openinghour_hours'),
    ]

    operations = [
        migrations.RunPython(create_sample_opening_hours),
    ]
