# Generated by Django 4.2.5 on 2025-01-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_openinghour_hours'),
        ('api', 'test_hours1'),
    ]

    operations = [
    ]
