# Generated by Django 4.2.5 on 2025-01-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_favorite_kebab_alter_favorite_user'),
        ('api', '0013_merge_0014_create_openinghour_test_hours1'),
    ]

    operations = [
    ]
