# Generated by Django 4.2.5 on 2025-01-17 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_merge_20250117_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='kebab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kebab'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kebab',
            name='google_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kebab',
            name='pyszne_rating',
            field=models.FloatField(default=0),
        ),
    ]
