# Generated by Django 4.2.5 on 2025-01-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_openinghour_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebab',
            name='closing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kebab',
            name='google_reviews_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kebab',
            name='opening_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kebab',
            name='pyszne_reviews_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kebab',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kebab',
            name='google_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kebab',
            name='pyszne_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
