# Generated by Django 4.2.5 on 2025-01-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_kebab_closing_year_kebab_google_reviews_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebab',
            name='pyszne_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
